### ISSUE TITLE
Downloading a DataDep from an `::AbstractPath`

### ISSUE THREAD

**Issue by nickrobinson251** [oxinabox/DataDeps.jl#100]
I'm trying to use DataDeps to download data from S3, where the remote path is an [S3Path](https://github.com/JuliaCloud/AWSS3.jl/blob/15be146b732438fa833f5e0b91e41f168cfdf8ae/src/s3path.jl#L1), like
```julia
register(DataDep(
    "MyData",
    "Is good data. Is in cloud",
    S3Path("s3://etc."),
    fetch_method=download
    ...
```

But when I call `datadep"MyData"` I get `MethodError: no method matching download(::S3Path, ::String)` (an `S3Path`  is not an `AbstractString`)

Is there a way around this? e.g. not using `@datasep_str` macro which returns a String.
Or would it require adding more support for AbstractPaths to DataDeps.jl, e.g. making datadeps themselves be Paths? #2

**Comment by oxinabox** [comment]
Work around is
```
fetch_method=String \circ download
```

**Comment by oxinabox** [comment]
I think using FilePaths.jl internally would be an enhancement. And would just solve this)
Including making `@datadep_str` return a FilePath.

That would be a relatively small, though breaking, change.

A much bigger change is DataDepsPaths.jl

**Comment by nickrobinson251** [comment]
The workaround doesn't work

**Comment by oxinabox** [comment]
Maybe lowercase `string`?

**Comment by nickrobinson251** [comment]
Also doest work.

Which I think makes sense because it's fails on download Which is called first

**Comment by oxinabox** [comment]
That used to work. Either FilePathsBase, or S3Paths broke this.

Oh S3Paths no longer provides a `download` function that accepts the local path (i.e. the save location) as a string.

Fix it there. Maybe using the `FilePaths.@compat` macro .

**Comment by nickrobinson251** [comment]
hmmm, so patching FilePaths with
```
julia> Base.splitext(p::AbstractPath) = filename(p), extension(p)

julia> Base.download(url::AbstractPath, localfile::AbstractString) = cp(url, Path(localfile); force=true)
```

I now get an error on `post_fetch_method=unpack`
```
Do you want to download the dataset from s3://MyData/v0.2.0/testdata.tar.gz to "/Users/nick/.julia/datadeps/MyData-v0.2.0"?
[y/n]
y
ERROR: ArgumentError: I don't know how to unpack /Users/nick/.julia/datadeps/MyData-v0.2.0
Stacktrace:
 [1] unpack_cmd(::PosixPath, ::String, ::SubString{String}, ::String) at /Users/nick/.julia/packages/DataDeps/RYAia/src/post_fetch_helpers.jl:19
 [2] #unpack#29(::Bool, ::typeof(unpack), ::PosixPath) at /Users/nick/.julia/packages/DataDeps/RYAia/src/post_fetch_helpers.jl:59
 [3] unpack at /Users/nick/.julia/packages/DataDeps/RYAia/src/post_fetch_helpers.jl:59 [inlined]
 [4] #18 at /Users/nick/.julia/packages/DataDeps/RYAia/src/resolution_automatic.jl:122 [inlined]
```

Sorry for the live debug -- trying to figure out where this issue belongs (here or FilePathsBase)

**Comment by oxinabox** [comment]
Now add the `string \circ ...`

**Comment by nickrobinson251** [comment]
haha, sorry I should add ...an all cases i tried with `fetch_method` equal to `download`, `string  \circ download` and `String \circ download`

**Comment by oxinabox** [comment]
Hmm. I believe in you. I am sure you will solve this. 
Meanwhile 🛫🌴 now.

**Comment by rofinn** [comment]
I'm fine to add a fallback in FilePathsBase for now (though I'm pretty sure this was defined for our internal S3Path specifically), but what should clarify the behaviour. Typically, `download(url, dst)` returns the `dst`, so in this case should that be a string even though some of the arguments are paths?

**Comment by oxinabox** [comment]
> In our case, we supported the second argument being a directory where the file should be downloaded into. 

DataDeps supports that too, infact, requires it.
That is what the [default download method does.](https://github.com/oxinabox/DataDeps.jl/blob/936f31532b3ae6745202fc82ed5941c10c5473e7/src/fetch_helpers.jl#L48)
(Based on `HTTP.download` not `Base.download` (which does not support this).

DataDeps requires that that `fetch_method(src, localdir)` 
should take in a local directory path, and  
should return the `localpath` of what was downloaded.
(*not* the the directory that it was download into.)
https://github.com/oxinabox/DataDeps.jl/blob/936f31532b3ae6745202fc82ed5941c10c5473e7/src/resolution_automatic.jl#L99

`download(s3path, localdir)` writes a file into `localdir` deleting any directory that was there.
Which I think is a bug in either FilePathsBase, or in AWSS3 (If I knew which I wouild open a bug report their).
This is not the behavour of `Base.download` (which would error), or `HTTP.download` which would download into (`HTTP.download is the behavour we want`)

I would expect `download(s3filepath, localdir)` to return `joinpath(localdir, basename(s3filepath))`
and `download(s3dirpath, localdir)` to return `joinpath(localdir, dirname(s3dirpath))`
That seems the most useful behavour.
And I don't think it conflicts with `Base.download` since `Base.download` errors in this case anyway.
I would call this operation `download` and it is distrinct from `cp`/`copy`.
Because it has this behavour. (`cp` should error if you tries to copy a file into the location of an existing directory without some kinda `force` argument. )

## Demos
### `HTTP.download` downloads into directories
```
julia> using HTTP

julia> HTTP.download("http://test.greenbytes.de/tech/tc2231/inlwithasciifilenamepdf.asis", localdir2)
"/Users/oxinabox/temp/demo2/foo.pdf"
```

### `Base.download` errors if second argument is a directory

```
julia> localdir3 = "/Users/oxinabox/temp/demo3"
"/Users/oxinabox/temp/demo3"

julia> isdir(localdir3)
true

julia> Base.download("http://test.greenbytes.de/tech/tc2231/inlwithasciifilenamepdf.asis", localdir3)
┌ Error: Download failed: curl: (23) Failed writing body (0 != 830)
└ @ Base download.jl:43
ERROR: failed process: Process(`/usr/bin/curl -s -S -g -L -f -o /Users/oxinabox/temp/demo3 http://test.greenbytes.de/tech/tc2231/inlwithasciifilenamepdf.asis`, ProcessExited(23)) [23]
```


### S3Path deletes directories and replaces them with files

```
julia> using FilePathsBase

julia> using AWSS3

julia> s3file = S3Path("s3://eis0p6-jobresultsbucket-8z4lory3ogew/backrun/2019-08-21T13h41m532/grid=PJM/sim_now=2018-07-09T10:00:00-04:00/BidFinance/financial_data.jlso")
p"s3://eis0p6-jobresultsbucket-8z4lory3ogew/backrun/2019-08-21T13h41m532/grid=PJM/sim_now=2018-07-09T10:00:00-04:00/BidFinance/financial_data.jlso"

julia> localdir = p"/Users/oxinabox/temp/demo"
p"/Users/oxinabox/temp/demo"

julia> isdir(localdir)
true

julia> download(s3file, localdir)
p"/Users/oxinabox/temp/demo"

julia> isdir(localdir)
false

julia> isfile(localdir)
true
```


(* the reason DataDeps.jl requires that the `fetch_method` take in a local directory, and return a local path to what was downloaded is that for some protocols (HTTP), there is no way to realiably determine what somethings name will be without actually at least initiating the  download of it. So DataDeps hands that duty of working out what the localpath should be to the `fetch_method`)

**Comment by oxinabox** [comment]
Why do you not agree with the `HTTP.download` behaviour?

It was the behaviour of AWSTools until the last set of breaking changes. Since `fetch_method=String \circ download`
 used to work.
And the requirements of DataDeps have not changed.
