### ISSUE TITLE
Conflicting File Name Resolution

### ISSUE THREAD

**Issue by mileslucas** [oxinabox/DataDeps.jl#121]
I have a somewhat unfortunate use-case: I have multiple remote files with the same name (which have different contents). I'm trying to figure out how to make download both and manually resolve the names.

Here are the source URLs
```
"https://github.com/carlgogo/VIP_extras/raw/master/datasets/naco_betapic_cube.fits"
"https://github.com/carlgogo/exoimaging_challenge_extras/raw/master/naco_betapic_cube.fits"
```
in practice, I want the first path to resolve locally to `"naco_betapic_cube.fits"` and the second to resolve to `"naco_betapic_cube_empty.fits"`.

In the documentation it seems like the `post_fetch_method` can't quite do that since it has no knowledge of the remote both. If the download order is deterministic, I could hack together something that checks if the file exists and renames it, but that feels very ad-hoc and fragile. Any tips or ideas?

**Comment by oxinabox** [comment]
The problem with `post_fetch` is first everything is `fetched` then everything is `post_fetch`ed.
By which point it is too late as the download has already overwritten one of them i guess.

What you could do is a custom `fetch_method`, to both download and rename.

The following works:
```julia
DataDep(
    "FITSDATA",
    "message",
    [
        "https://github.com/carlgogo/VIP_extras/raw/master/datasets/naco_betapic_cube.fits",
        "https://github.com/carlgogo/exoimaging_challenge_extras/raw/master/naco_betapic_cube.fits",
    ];
    fetch_method = [
        DataDeps.fetch_default, # for first use default method

        # for second use a custom method that directly downloads to our chosen file-name
        (remote_path, localdir) -> DataDeps.HTTP.download(remote_path, joinpath(localdir, "naco_betapic_cube_empty.fits"))
    ]
)
```

You will need the latest release of DataDeps, as I had to quickly fix a typo.
Turns out noone has ever used the feature where we support using different `fetch_method`s for different files, and it has a 1 character typo.

---

Aside: recommend against downloading direct from Github, they hate that,
and using a something like https://raw.githack.com/
which puts a CDN infront.

**Comment by mileslucas** [comment]
> using a something like raw.githack.com

thanks for the tip!

> You will need the latest release of DataDeps

Wonderful, thanks for the quick response and solution! I'll hook it up and let you know if anything goes wrong.

**Comment by mileslucas** [comment]
Here's something I noticed; not sure if it is a bug or not-

The file requiring the custom fetch seems to evade the logging filter from `DATADEPS_ALWAYS_ACCEPT` (see: https://juliahci.github.io/ADI.jl/previews/PR19/examples/betapictoris/#Data-Reduction-1)

**Comment by mileslucas** [comment]
Ah, okay- not a bug, just need to add a little more to the custom function:

```julia
# use a custom method that directly downloads to our chosen file-name
function rename_download(remote_path, localdir)
    update_period = DataDeps.progress_update_period()
    DataDeps.HTTP.download(
        remote_path,
        joinpath(localdir, "naco_betapic_cube_empty.fits");
        update_period=update_period
    )
end
# inside register block
fetch_methods = [fetch_default, rename_download]
```
