### ISSUE TITLE
Disable prompts in CI

### ISSUE THREAD

**Issue by alyst** [oxinabox/DataDeps.jl#70]
Would it be possible to automatically detect CI (get(ENV, "CI")) and disable the prompt in that case?
If it's CI session and DATADEPS_ALWAYS_ACCEPT is false/not set that should probably result in an error in download()?

**Comment by oxinabox** [comment]
Anything is possible.
The real question is, is it a good idea?  
Maybe.


Possibly a check thing in that occurs when the module is loaded.
Something like the following would work.

```
function __init__()
    if env_bool("CI")
	    # Probably in a CI environment
		if !haskey(ENV, "DATADEPS_ALWAYS_ACCEPT")
		    # No user settings for ALWAYS_ACCEPT or not
			ENV[DATADEPS_ALWAYS_ACCEPT]=true
			@info """Detected that probably in a CI environment,
					 DATADEPS_ALWAYS_ACCEPT unset: defaulted to true.
					 If this is incorrect please set DATADEPS_ALWAYS_ACCEPT to false.
					 Or to suppress this message, set DATADEPS_ALWAYS_ACCEPT to true.
					 Then restart the program.
				  """
		end
    end
end
```


However, I am very cautious about bypassing the accept prompt.
Because sometimes it has an EULA in it.
Like in the dataset in https://white.ucc.asn.au/2018/07/14/Asynchronous-and-Distributed-File-Loading.html

By making the user set the environment variable in the CI config,
as in https://github.com/JuliaText/Embeddings.jl/blob/e70d018b7f082db55df5050b14c5f51458352ac2/.travis.yml#L16
It confirms that they are actively deciding to do this.
Vs doing it automatically ...

**Comment by andreasnoack** [comment]
It think it is a good idea. Nirx.jl has just produced a 112GB log file almost only containing
```julia
Do you want to download the dataset from ["https://s3.amazonaws.com/test.robertluke.net/fNIRS-test-data.zip"] to "/home/jrun/NIRX/.julia/datadeps/NIRX test file 1"?
[y/n]
```

**Comment by oxinabox** [comment]
> I just propose that DataDeps throws an error (similar to the one you have outlined)

Ah, just throwing an error if, `CI` is set, and `DATADEPS_ALWAYS_ACCEPT` has no value.
I think that makes sense. It avoids any question of if ambiguity as to if they wanted to accept or not.

----

@andreasnoack  I am sorry, man DataDeps is really smashing the logs files on infrastructure.
I don't understand why it would repeat that output though, that is weird.

**Comment by oxinabox** [comment]
Closed in 
https://github.com/oxinabox/DataDeps.jl/commit/e457418e897a3e1be50ffa7d3c1589a3d905166f

Which should have been a PR. but I failed at git, and pushed to master.
Tests pass on travis so I believe I am all good.
